<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsqd2yl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsqd2yl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWsqd2yl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWsqd2yl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWsqd2yl\appDevDebugProjectContainer([
    'container.build_hash' => 'Wsqd2yl',
    'container.build_id' => 'f9cbd436',
    'container.build_time' => 1554987842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsqd2yl');
